### ISSUE TITLE
Jsx-ally onChange vs. onBlur

### ISSUE THREAD

**Issue by Nayshlok** [WTW-IM/es-components#105]
When working with the jsx-ally in eslint the following error appears

C:\Dev\Source\es-components\src\components\patterns\datepicker\DatePicker.specs.js
  18:7  error  onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/use-onblur-not-onchange

The challenge is I know onBlur and onChange do not do the same thing, and as such I do not see them being interchangeable. Do you need to change the lint rule globally, or do we make the change to our code?

**Comment by Darrken** [comment]
Did you configure your .eslint file to use the recommended or strict ruleset? I'm using recommended and I'm not seeing this warning.
