### ISSUE TITLE
Investigate Different Approach to nested ThemeProviders

### ISSUE THREAD

**Issue by aabenoja** [WTW-IM/es-components#123]
The mantra so far has been that we need to supply the theme to a `ThemeProvider` only once and the changes will trickle down, but this becomes a little difficult to maintain when children contain their own `ThemeProvider` with a default prop value of `defaultTheme`. Currently simply passing the theme as a prop will resolve all these situations, but I wonder if we need to spend a little more time thinking about how we want to approach nested `ThemeProviders` in general.

Per documentation `styled-component` does provide a [withTheme HoC](https://www.styled-components.com/docs/advanced#theming) that could resolve these issues in a potentially more elegant manner. To use #122 as an example:

```js
import styled, { ThemeProvider, withTheme } from 'styled-components';
import ToggleButton from './path/to/ToggleButton';

const ThemedToggleButton = withTheme(ToggleButton);
```

My only issue with this approach is that this is effectively the same as the solution proposed in #122, only obfuscated by the `withTheme` HoC. On one hand, we define the theme for the theme provider once and don't pass it around, which we want, but on the other it's a bit heavy handed. I'm leaning a little towards using the HoC since it does make the jsx just slightly cleaner.

Another vein of thought to explore could be using `withTheme` in place of `ThemeProvider` in components we know for sure will be wrapped with `ThemeProvider` in some parent, but I have no idea what guarantees we have in avoiding the current problem.

---

### Affected Locations
* #122 
* #127

**Comment by aabenoja** [comment]
It is preferable to maintain our current approach of simply importing and dropping in components as needed without worrying about passing theme or wrapping our imports. Another approach that I'm leaning towards is the inverse where we wrap our **exports** with `withTheme`. In the example of button:

```js
export default withTheme(Button);
```

This results in the following jsx body when rendered

```jsx
<WithThemeButton>
  <Button>
    <ThemeProvider>
      { content }
    </ThemeProvider>
  </Button>
</WithThemeButton>
```

This approach maintains our ease of usability and styling and will respect all sources for theme in the following order

1. Use the `theme` prop, if provided
2. Will pull `theme` from the context provided by a parent `ThemeProvider`
3. Fallback to the theme provided by default props, if any

**Comment by Darrken** [comment]
I really like this export approach, @aabenoja!

**Comment by Darrken** [comment]
I've been messing around with this and I'm wondering if we just need to require a ThemeProvider around our components or the consuming app and *not* in each of our components.  Reading the [Theme docs](https://www.styled-components.com/docs/advanced#theming) it sort of sounds like only styled components have access to the ThemeProvider context, and using the withTheme HOC only makes that theme context available to your component too. I'm a little confused about that.

I wonder if setting a default theme in each component and accepting it as a prop is messing up the intended behavior. I would think wrapping the components externally with the ThemeProvider should be enough, but testing today has shown me in many cases I have to also pass the theme as a prop to make it use a theme other than the default.
