### ISSUE TITLE
Error When Not Using Moment.js

### ISSUE THREAD

**Issue by scottoffen** [WTW-IM/es-components#130]
Compiling assets when not using the datepicker (only importing a simple button):

```js
import React from "react";
import ReactDOM from "react-dom";
import './styles/styles.css';

import Button from 'es-components';
import { ThemeProvider } from 'styled-components';
import { viaTheme } from 'es-components';

const App = () =>
  <div className="test">
    <h1>Colleague Portal</h1>
    <Button styleType="primary" isOutline style={buttonDemoStyle}>Primary</Button>
  </div>;

ReactDOM.render(
  <ThemeProvider theme={viaTheme}>
    <App />
  </ThemeProvider>,
  document.getElementById("app")
);
```

```
ERROR in ./node_modules/react-datepicker/es/index.js
Module not found: Error: Can’t resolve ‘moment’ in ‘/Users/ianlan/Projects/agent-management-suite/colleague-portal/app/node_modules/react-datepicker/es’
@ ./node_modules/react-datepicker/es/index.js 5:0-28 272:9-15 276:9-15 294:10-16 294:46-52 301:9-15 305:9-15 318:47-53 499:39-45 513:9-15 569:13-19 604:11-17 608:11-17 619:11-17 623:11-17
@ ./node_modules/es-components/lib/components/patterns/datepicker/DatePicker.js
@ ./node_modules/es-components/lib/index.js
@ ./src/index.js
@ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
```

If we aren't using the datepicker in our project, this should not be a required dependency.

> Using React 16.2

**Comment by jrios** [comment]
I am going to re-open this issue. @scottoffen has a very good point about the required dependencies. As it is right now, the module itself doesn't actually have good tree-shaking capabilities right now. so when a component is imported, the entire module ends up being included in the bundle. Any dependencies, including moment (which is very large), ends up ballooning the application's bundles.

I think it makes sense to expand the scope of this issue to include better modularity all around, so when a single component is included, only that component is included in the resulting bundle.

**Comment by aabenoja** [comment]
This is something I am tentatively working on with #76. I currently have a plan to include an `es6` build that will live alongside the `lib` directory that will contain a treeshaking-friendly build. The easiest way to integrate it would be for a downstream project to use a webpack alias on `es-components` to point to the `es-components/es6` so that they don't have to rewire every import. I could get a WIP PR up and running later today for this.

**Comment by aabenoja** [comment]
Just a quick anecdote on treeshaking, webpack v4 will only to only tree shake during production builds and will still import everything into the non-production bundles. In short the dev experience will still pull in everything, but prod builds will be optimized.
