### ISSUE TITLE
Styled-components should be set as a peer/dev dependency

### ISSUE THREAD

**Issue by Darrken** [WTW-IM/es-components#153]
When importing a library using styled-components into a project also using styled-components, conflicts occur. Due to this [issue](https://github.com/styled-components/styled-components/issues/1076) we need to move our styled-components dependency to peer & dev so the downstream app is only bundling one copy.

**Comment by aabenoja** [comment]
I just dropped in `styled-components@^3.2.6` as a dev dependency and set the peer dependency to `styled-components: >=2.4.0` and things seem to be working fine locally, though all I did was a quick `npm test`. Kinda surprised the snapshot classes were not impacted
