### ISSUE TITLE
Deprecate React peerDependency <= 16

### ISSUE THREAD

**Issue by jrios** [WTW-IM/es-components#204]
With more dependencies beginning to use React 16 features as their defaults, it might make sense to start thinking about how this project can also move in that direction.

What are your thoughts on moving forward with intentions of removing any version of React <= 16 as a peer dependency in the next major version?

**Comment by aabenoja** [comment]
Per https://github.com/WTW-IM/es-components/pull/201#issuecomment-422552837

>If we decide to lock into React 16, we will need to maintain two different branches of code just in case bug fixes need to be made. Perhaps a branch that can be made for React <= 16 and enforce React >= 16 in the mainstream branch.

> In that case I think we should hold off until v18 to do the react 16.3.0 stuff. I would like to have the process of working with the "legacy" branch and "mainstream" branches documented. This will also give me time to get the npm publish automation in place for the "legacy" branch.

**Comment by aabenoja** [comment]
As a followup to #215 I created [this branch](https://github.com/WTW-IM/es-components/compare/master...aabenoja:forward-inputref) that replaces the `DateTextbox` with`forwardRef`.

**Comment by jrios** [comment]
closing this in favor of #229
