### ISSUE TITLE
Use semantic-release

### ISSUE THREAD

**Issue by aabenoja** [WTW-IM/es-components#219]
This will afford us a couple of niceties
* Automatic version updates
* Automated changelog generation

## To Do
* [ ] Configure `semantic-release` to use lerna in the project root on merge to master
* [ ] Configure `changelog` publishing on merge to master
* [ ] Create custom prepare/release plugin
  * [ ] Run `lerna-publish`during prepare step
  * [ ] Push to npm during release step for each package

**Comment by aabenoja** [comment]
https://github.com/atlassian/lerna-semantic-release

**Comment by aabenoja** [comment]
@jrios @Darrken  `semantic-release` mostly works out of the box. Using `lerna-semantic-release` was a bit more convoluted to setup. The plugin system keeps things fairly simple in customizing our workflow. There are two basic items that need to be done:

1) If we want to use a custom commit message structure we can start looking at a way of extending the existing `@semantic-release/commit-analyzer`. We can mostly ignore this if we use one of the existing semantics.
2) The main lift is creating a plugin that hooks into the `prepare` and `release` steps to version bump each package. Part of the complication here is how strictly we want to maintain keeping the versions of all packages the same. `lerna` will not be version bumping the theme packages as frequently when this process is in place due to no changes taking place since the most recent git tag.

**Comment by Darrken** [comment]
I'm for sticking with an existing format that's already documented and proven over trying to come up with our own. I also don't mind if the themes have their own independent versions. Especially if they will be running under semantic release rules.

**Comment by aabenoja** [comment]
Just so we're clear, we're find with sticking with the angular conventions? You can see our other options in the `preset` section for the [commit-analyzer](https://github.com/semantic-release/commit-analyzer#options) options.

**Comment by Darrken** [comment]
I didn't mean the angular one specifically, just one of the existing presets. I kind of like the eslint one myself.

**Comment by aabenoja** [comment]
I'll need to double check something with that commit analyzer. When I tried a "build" update using the angular preset the version was not bumped. While it does make sense from a semver standpoint this does not align with our versioning rules.

@jrios How does using the [`eslint conventions`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint) sound to you?

**Comment by Darrken** [comment]
Do you have a preference based on the existing ones, or do we need to just
make our own? My point was to keep it simple, but if there aren't any that
fit our needs exactly then I'm fine with creating our own.

**Comment by aabenoja** [comment]
@jrios Issues are not required. I didn't see anything in the documentation, so I had to verify this in my branch. I also verified that the `Build` tag does not trigger a release. If we want to maintain our current convention of minior version bumps for build tool updates I could easily fork `conventional-changelog-eslint` to suit our needs.

**Comment by aabenoja** [comment]
Notes on additional tooling: to ensure commit messages are correctly formatted we could use something like `commitlint` with `@commitlint/config-conventional`. We can then safely decommission the version bot.
