### ISSUE TITLE
individual component packages

### ISSUE THREAD

**Issue by jrios** [WTW-IM/es-components#247]
I'm curious to hear thoughts on having each component be their own package. They would still live in this repository, we already have the ability to do multiple package publishing.

I think we get a huge benefit of being able to update and version each component independently. This would allow major changes to be made to individual components without requiring an update to downstream projects that don't use that changed component. 

However, there is still the drawback of each downstream project having to install each component they need independently. 

do y'all think this is something worth investing in? should we keep a single package *and* have individual component packages that can be installed independently?

**Comment by Darrken** [comment]
That's not a bad idea. A lot of libraries out there do that, and it makes
sense considering how much you'd save only importing what you needed. How
do you see the changelog working if we went this route? Would it still be
the single source for updates, or would we add tags/labels with notes to
each component?

**Comment by sbartlett** [comment]
I agree that we would save on import cost, and making updates would be a lot easier, but I do see a some problems coming up from things like change tracking and notifying down stream to changes which is something we already haven’t been good at. 

After we get those things resolved I think this is definitely something to look at.

**Comment by aabenoja** [comment]
Lerna does exactly this. Each of its commands are all published into their own packages in the `@lerna` scope. The `lerna` package then installs each of them while providing the primary `cli`.

We could achieve similar

```
es-components
├── index.js
├── @es-components/base
├── @es-components/controls
```

with `es-components` existing as a convenience layer.

One of the issues I foresee is cross-dependencies, such as the necessity for `ToggleButton` on `Menu`. I have no idea how we would split it apart, but for this scenario let's say buttons have been split into their own package. We push Menu into into a different one. In order for `Menu` to function we have two options.

1. Make the buttons package a dependency of the `Menu` package (or whatever it's called)
2. Make the buttons package a peer dependency

With the first approach we can have multiple versions of the buttons package. The downstream project can have both the buttons and menu packages as dependencies, with the buttons package potentially a major version higher than what menu needs. This is both good and bad, as menu can function a la carte without whatever breaking changes were introduced in the later version of buttons, it just needs to be updated separately.

If we go the peer dependency approach that can be a lot of peer dependencies for the user to worry about. If they use multiple smaller packages we do not run into the potential version collisions we would see with the `dependencies` approach, but that can be a large number of cross dependencies to leave to the user.

**Comment by mike-schenk** [comment]
I understand the benefit Jake points out in being able to update and version each component independently. But I don't see there being much benefit in "import cost." By the time you've imported probably four or five components, it'll probably not be any more efficient than having imported one large package (I'm thinking here of the `npm install` experience).

Another consideration I want to throw out is how this decision might affect the way these components might be distributed (to end-users) via CDN. 

I think a goal ought to be to maximize the reusability of scripts cached in browsers. We expect these components to be used on multiple (micro)sites. Probably hosting individual components in individual versioned scripts on a CDN achieves maximum reusability as long as the CDN supports HTTP/2 to mitigate the performance hit of a potentially large number of script files to download.

If not using a CDN, smart bundling and tree-shaking in WebPack can avoid sending the unnecessary code to end-users even while this continues to be distributed in a single package.

But a competing goal is to make the developer experience simple. Now it's really easy to import this one package, then refer to the documentation and start using any of the components that are provided. It would annoy me as a developer to have to keep going back and installing a new package the first time I want to use a component, I'll never remember if I already installed it in my project.

To Alex's point, splitting them up only really works effectively if you can eliminate the cross-dependencies... and that seems... hard.

My vote is to keep it a single package unless you can break the cross-dependencies and somehow find a way for the development experience to be as productive as installing and tracking a single package dependency.

**Comment by jrios** [comment]
thanks for everyone's comments. the biggest benefit really is that components can be versioned independently which could give people a bit more freedom to making changes to components as necessary. 

the big takeaway is that we need to have more governance around major version updates so that when a new major version is released, it is purposeful and includes things like a migration guide, changelog, etc. This also means that we need to strive to make backwards compatible changes when possible.

I'm going to close this with the intention to continue with the single package.

if we need to revisit, we can reference or reopen this issue.
