### ISSUE TITLE
document namespaced components

### ISSUE THREAD

**Issue by jrios** [WTW-IM/es-components#253]
Let's come to an agreement about whether or not to include documentation about namespaced components like `Drawer.DrawerPanel`, `Modal.Header`, etc.

**Comment by aabenoja** [comment]
I am also for not including them. The name of the component does not necessarily match the usage with it's parent component, such as `HorizontalNavItem` in #252. While it can be easy to figure out how these components map to our API that is still some cognitive overhead when trying to quickly lookup the documentation.
