### ISSUE TITLE
IE11 - Tooltips do not work

### ISSUE THREAD

**Issue by jrios** [WTW-IM/es-components#414]
Tooltips throw an error when rendering in IE11. `TypeError: Object doesn't support property or method 'getRootNode'`

`getRootNode` is not supported in IE11

**Comment by Darrken** [comment]
I'm guessing this also affects Popover since that also uses the `useRootNode.js` file that has that call.

**Comment by stevematney** [comment]
There's a [`getRootNode` polyfill](https://github.com/foobarhq/get-root-node-polyfill) we could load. It's very small.

**Comment by jrios** [comment]
Yes, I think that is the right solution. I just didn't have the time to implement it yesterday. If someone has the time to take this on before I get to it this afternoon, that'd be great.

**Comment by stevematney** [comment]
I wanna try to get `useRootNode` working for popups, so I'll do this piece first and then do that.
