### ISSUE TITLE
Allow buttons to be rendered as anchors

### ISSUE THREAD

**Issue by Tevyn** [WTW-IM/es-components#461]
We should probably have an IsAnchor prop or something similar on Buttons that renders them as actual anchor tags instead of buttons.

This will mean more consistent semantics and better accessibility for when the button's action is to link someone to another page.

**Comment by jrios** [comment]
We don't need this. Use the `as` prop to render a button as an anchor tag:

`<Button as="a" href="https://www.google.com" styleType="primary">Go to Google</Button>`

**Comment by Darrken** [comment]
If you need an anchor tag, we have the `Anchor` component that styles an anchor according to the BDA designs. If you need a `Button` to *look* like an anchor, we have `LinkButton`.

**Comment by stevematney** [comment]
One thing we could do is add a note about `as` in the docs, even if we just link off to the [styled-components docs about it](https://styled-components.com/docs/api#as-polymorphic-prop).

**Comment by sviridovdy** [comment]
@stevematney, yes. That would be helpful.
