### ISSUE TITLE
useWindowWidth ignores body margin.

### ISSUE THREAD

**Issue by sviridovdy** [WTW-IM/es-components#467]
If `body` has a margin of X px then `useWindowWidth()` will return window with - (`margin-left` + `margin-right`)
This makes using this function to match css media query in js impossible since css media query (like `max-width`) will include body margins.
Is it possible to use something else instead of `document.body.clientWidth`?

**Comment by stevematney** [comment]
It looks like `useWindowWidth()` is [already using `document.body.clientWidth`](https://github.com/WTW-IM/es-components/blob/master/packages/es-components/src/components/util/useWindowWidth.js#L8)

**Comment by Darrken** [comment]
Could you provide a jsfiddle or something demonstrating this? From what I can see, both `document.body.clientWidth` and `document.documentElement.clientWidth` return the same things, and do not include the margins.

The [MDN Web docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) say that these uses of clientWidth should be special cases that return the full viewport width minus the scrollbar only, and that's what I'm seeing with a simple test.

No margins:
![image](https://user-images.githubusercontent.com/797074/90530345-05320500-e132-11ea-823e-81dc5148f82f.png)

Body margin of 500px, inner wrapper of 50px:
![image](https://user-images.githubusercontent.com/797074/90530269-e92e6380-e131-11ea-9682-bd299d841fd5.png)

**Comment by Darrken** [comment]
It sounds like using `document.documentElement.clientWidth` may be a safer option because it doesn't have the quirks-mode caveat.

**Comment by sviridovdy** [comment]
Try to change width between 500 and 600 px
https://jsfiddle.net/manhust/j0tdrsyk/
