### ISSUE TITLE
Parity issues between BDA Toolkit, Sketch and ES Components

### ISSUE THREAD

**Issue by bradyclifford** [WTW-IM/es-components#580]
There is a discrepancy in colors and icons between BDA Toolkit, Sketch and ES Components.

BDA Toolkit is the standard.

![image](https://user-images.githubusercontent.com/8923247/132883148-41eeab6c-591a-47ee-8f28-e50544801faa.png)
> A better comparison will be provided

[BDA Differences in details](https://drive.google.com/file/d/1b81vTb6ZlBbUL1uT5e_UwnQ2NKU5p8sa/view?usp=sharing)

**Comment by bradyclifford** [comment]
Is there a reason why we are not using the BDA toolkit's css in ES Components?  That way we don't have to manually keep them both up to date?

**Comment by bradyclifford** [comment]
Paul Zak is leading the charge with this in conjunction with Tim Fleming.

**Comment by gcolbath** [comment]
> Is there a reason why we are not using the BDA toolkit's css in ES Components? That way we don't have to manually keep them both up to date?
> 
> Be nice if we had full access to the BDA toolkit CSS in our projects.

This is an excellent question, @bradyclifford! It's certainly something that's been pondered in the past. It would be great to have fewer "'sources' of 'truth'"—i.e.: for UX and engineering to have the same rulebook—and I think that will be something that's discussed as part of the topics brought up via @stevematney's ADR proposal. I believe there will be some discussion pertaining to the latter happening at the upcoming Client PF Architectural Summit, too.

**Comment by gcolbath** [comment]
> Paul Zak is leading the charge with this in conjunction with Tim Fleming.

Also, for the record, I'm scrubbing in on this. Paul reached out to me, just a little bit ago, bringing the issue to my attention (and then I saw there was a gh issue about the very same topic!).

**Comment by bradyclifford** [comment]
> It's certainly something that's been pondered in the past. It would be great to have fewer "'sources' of 'truth'"—i.e.: for UX and engineering to have the same rulebook—and I think that will be something that's discussed as part of the topics brought up via @stevematney's ADR proposal. I believe there will be some discussion pertaining to the latter happening at the upcoming Client PF Architectural Summit, too.

Sounds good.  Where is this ADR @stevematney  put together?  I would like to look it over.

Love to be a fly on the wall for the Client PF Architecture Summit.  You happen to forward me the invite for that or get me in touch with the organizer?

**Comment by gcolbath** [comment]
@bradyclifford – sure thing! Brooks Yates is organizing it, but I'll put in a word for you (or otherwise forward you the invite 😉). @stevematney's "ADR proposal" is the "Website Platform Bounded Context" PR found here: https://github.com/im-practices/master-architecture-plan/pull/260
