### ISSUE TITLE
Popover Placement In Mobile

### ISSUE THREAD

**Issue by aabenoja** [WTW-IM/es-components#62]
As mentioned in #61 we probably need a little bit more thought in how we handle popovers in the mobile view. I keep thinking that we should probably default to using bottom placement always for mobile, that way the user is able to see the top of the content body. Your thoughts, @Darrken?

**Comment by Darrken** [comment]
That sounds reasonable. I'd like to see some examples too, and check bootstrap's method of handling this (if any).

**Comment by Roughnick** [comment]
Making the popover 100% of the view should hopefully fix this issue 

![2018-03-12_10h42_38](https://user-images.githubusercontent.com/3384059/37297318-fa367a44-25e2-11e8-9a02-c45d1d55fc2c.png)
![2018-03-12_10h43_15](https://user-images.githubusercontent.com/3384059/37297330-017626f6-25e3-11e8-96a0-d8f6b9f50af2.png)

**Comment by Darrken** [comment]
Maybe we should just retool the popover to style/wrap the latest bootstrap version.

**Comment by KeionneDerousselle** [comment]
I'm not sure if this is the right issue to submit this under, but I've noticed that the popover doesn't stay next to it's associated text when resizing the window.

![2018-05-14_11h04_30](https://user-images.githubusercontent.com/6044786/40012257-55380ae2-5767-11e8-828d-176755377073.gif)

Not sure how the current implementation works, but I've seen other react component libraries use [rc-tooltip](https://www.npmjs.com/package/rc-tooltip) to achieve this. I believe this library just calculates the absolute positioning based on screen size. It's relatively lightweight and easy to customize. 

Not sure if this is the kind of route we'd like to go, but it might be worth looking into.

**Comment by Darrken** [comment]
@KStClaire is working on a popover rewrite that is pretty close to being pulled in. She may have addressed this issue in that PR.

**Comment by KeionneDerousselle** [comment]
@Darrken Thanks! I'll get in touch with her or pull down a branch if she has one.

**Comment by KStClaire** [comment]
@KeionneDerousselle You can find the popovers branch on [my fork](https://github.com/KStClaire/es-components/tree/popovers) of es-components. Let me know if you have any issues with anything.

**Comment by KeionneDerousselle** [comment]
Thanks @KStClaire

**Comment by jrios** [comment]
@KStClaire @Darrken has this been merged? can we close this issue?

**Comment by Darrken** [comment]
The new popover has been merged. It looks like Keionne's issue was taken care of by the change, but there is still some quirkiness with the left and right popover placement in a mobile view. At least from local testing using dev tools in iphone view.

**Comment by Darrken** [comment]
@KStClaire Did this get resolved with your latest updates?

**Comment by KStClaire** [comment]
@Darrken Yes, this should have been resolved with my last updates.

**Comment by Darrken** [comment]
Addressed in #176 (or before)
