### ISSUE TITLE
Popover hasAltCloseButton prop prevents screenreader from reading content

### ISSUE THREAD

**Issue by Darrken** [WTW-IM/es-components#815]
When using the `hasAltCloseButton` prop in a `Popover`, it prevents the Window Narrator screen reader from continuing past the title and skips the popover body content. I'm not sure if this affects other screen readers, but it's easily reproduceable using the Windows built-in one.

Steps to reproduce:
1) https://wtw-im.github.io/es-components/#!/Popover/4
2) Activate Windows Narrator with Windows key + CTRL + Enter
3) Click on the popover link (question mark icon in this example)
4) Screen reader only reads "Icon popover"

Remove `hasAltCloseButton` from the example and redo the above steps and the content "Here's some help text!" is read.

**Comment by stevematney** [comment]
We believe this has been resolved. Please let us know if the issue persists! :smile:
