### ISSUE TITLE
Textbox components will cause snapshots to fail in consuming projects

### ISSUE THREAD

**Issue by jrios** [WTW-IM/es-components#95]
If a consuming project is using the `Textbox` component and uses snapshot testing in Jest, the snapshot will consistently be updated causing failed snapshots over and over.

The cause of this is the [`genId()`](https://github.com/WTW-IM/es-components/blob/master/src/components/controls/textbox/Textbox.js#L130) function call inside of the Textbox component. It should be safe to get rid of this call and use the [`name prop`](https://github.com/WTW-IM/es-components/blob/master/src/components/controls/textbox/Textbox.js#L129) for the id of the input in order to maintain the for/id relationship which is important for accessibility.

**Comment by jrios** [comment]
It's also possible that the same problem could occur when using the [`helpId`](https://github.com/WTW-IM/es-components/blob/master/src/components/controls/textbox/Textbox.js#L111). I haven't tried that personally, but I imagine it will have the same issue because it gets invoked and creates a new ID every time it renders.

**Comment by Darrken** [comment]
The test is mocking the generateAlphaName function with a persistent value which should have prevented this (the drawer tests also use it).  I agree the name prop could be used, but we should make it required in that case.

**Comment by jrios** [comment]
I pushed a fix to this in #94. You can see f685a62 for the fix I pushed.
